service: job-system

custom:
  jobsTableName: ${self:service}-${sls:stage}-jobs
  jobsQueueName: ${self:service}-${sls:stage}-jobs-queue
  jobsDlqName: ${self:service}-${sls:stage}-jobs-dlq
  cognitoUserPoolId: eu-central-1_neVVyaSp4
  cognitoAppClientId: 1q3rk6ierkvgb3jlae7d320q6f

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.cognitoUserPoolId}
        audience:
          - ${self:custom.cognitoAppClientId}
  environment:
    JOBS_TABLE_NAME: ${self:custom.jobsTableName}
    JOBS_QUEUE_URL:
      Ref: JobsQueue
    SES_FROM_EMAIL: erdemootv1@gmail.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - !GetAtt JobsTable.Arn
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt JobsQueue.Arn
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "*"

functions:
  createJob:
    handler: src/handlers/createJob.handler
    events:
      - httpApi:
          path: /jobs
          method: post
          authorizer:
            name: cognitoJwtAuthorizer

  getJob:
    handler: src/handlers/getJob.handler
    events:
      - httpApi:
          path: /jobs/{id}
          method: get
          authorizer:
            name: cognitoJwtAuthorizer

  processJob:
    handler: src/handlers/processJob.handler
    events:
      - sqs:
          arn: !GetAtt JobsQueue.Arn
          batchSize: 1
          maximumRetryAttempts: 2
  listJobs:
    handler: src/handlers/listJobs.handler
    events:
      - httpApi:
          path: /jobs
          method: get
          authorizer:
            name: cognitoJwtAuthorizer

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.jobsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    JobsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.jobsQueueName}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt JobsDlq.Arn
          maxReceiveCount: 3

    JobsDlq:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.jobsDlqName}